title:              Yun Blog
email:              yuyun0124@gmail.com
description:        Study Blog
author:             YunYongWoon
baseurl:            ""
url:                "https://yunyongwoon.github.io"

# Social Profiles
twitter_username:   YunYongWoon
github_username:    YunYongWoon
facebook_username:  YunYongWoon
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
